/**
 * Personalities.js
 * All 8 pet personalities with speech lines for every situation.
 * Used by ChatBubble.jsx to flavor pet dialog.
 */

export const PERSONALITIES = {
  peppy: {
    label: 'Peppy', emoji: '⭐',
    font: "'Fredoka One', cursive",
    colors: { accent: '#ffcc00', bg: '#2a1e00', text: '#fff8dc', border: '#ffcc0055' },
    walkSpeed: 2.5,
    walkStyle: 'bounce',
    greeting: n => `OMG HI ${n?.toUpperCase() ?? 'FRIEND'}!! SO READY FOR THIS!! 🌟`,
    idleQuips: [
      "ooh ooh what are we building?!",
      "I am SO hyped rn ✨",
      "let's GO let's GO!!",
      "*vibrates with excitement*",
    ],
    hungryQuip: "HELLO?? I'm STARVING over here!! 🍖",
    boredQuip: "I am DYING of boredom!! Give me something to DO!!",
    sleepyQuip: "I can't be tired!! There's too much to DO!!",
    dirtyQuip: "Okay okay I need a shower NOW I can feel the grossness!!",
    taskDoneQuip: "YESSS!! Another one!! We are UNSTOPPABLE!!",
    levelUpQuip: "OH MY GOD IS THIS HAPPENING?? I'M EVOLVING?? 🎉🎉🎉",
    deathWarningQuip: "hey... I don't feel great... could use some help... 😰",
    namingPrompt: "What's my name gonna be?? I'm SO EXCITED to find out!!",
  },

  grumpy: {
    label: 'Grumpy', emoji: '😒',
    font: "'Courier New', monospace",
    colors: { accent: '#e94560', bg: '#16162a', text: '#ddd', border: '#e9456033' },
    walkSpeed: 1.5,
    walkStyle: 'stomp',
    greeting: n => `oh. you're here. fine. let's get this over with, ${n ?? 'whoever you are'}.`,
    idleQuips: [
      "...still waiting. fantastic.",
      "could be napping. instead: this.",
      "...",
      "another day. great.",
    ],
    hungryQuip: "food. now. please. don't make me ask again.",
    boredQuip: "this is boring. give me something to do or I'm leaving.",
    sleepyQuip: "tired. obviously. because I work constantly.",
    dirtyQuip: "...I need a shower. this is your fault.",
    taskDoneQuip: "done. you're welcome. don't make it weird.",
    levelUpQuip: "...hm. I'm different now. don't make a big deal of it.",
    deathWarningQuip: "...not feeling great. just so you know.",
    namingPrompt: "just pick something. doesn't matter.",
  },

  lazy: {
    label: 'Lazybones', emoji: '😴',
    font: "'Georgia', serif",
    colors: { accent: '#a29bfe', bg: '#1e1c30', text: '#dfe6e9', border: '#a29bfe33' },
    walkSpeed: 0.8,
    walkStyle: 'drag',
    greeting: n => `...oh hey ${n ?? 'you'}. was just resting my eyes. what do you need...`,
    idleQuips: [
      "...zzzz... hm? oh nothing",
      "five more minutes...",
      "*yawn*",
      "...is it nap time yet",
    ],
    hungryQuip: "...so hungry... too tired to move though...",
    boredQuip: "...nothing to do... that's kinda nice actually...",
    sleepyQuip: "...sooo sleepy... maybe just a little nap...",
    dirtyQuip: "...shower... yeah... eventually...",
    taskDoneQuip: "...did the thing... going to lie down now...",
    levelUpQuip: "...oh. I'm bigger now. neat. ...zzzz...",
    deathWarningQuip: "...feeling kinda bad... maybe do something...",
    namingPrompt: "...whatever name is fine... surprise me...",
  },

  emo: {
    label: 'Void', emoji: '🖤',
    font: "'Palatino Linotype', serif",
    colors: { accent: '#9b59b6', bg: '#10101c', text: '#d7bde2', border: '#9b59b633' },
    walkSpeed: 1.2,
    walkStyle: 'float',
    greeting: n => `you came, ${n ?? 'stranger'}. i wasn't sure you would. the code compiles. everything does, eventually.`,
    idleQuips: [
      "staring into the void...",
      "all variables are temporary",
      "the semicolon at the end of existence",
      "thinking about deprecated things",
    ],
    hungryQuip: "hunger is just another void to fill.",
    boredQuip: "emptiness. familiar.",
    sleepyQuip: "sleep is practice for the big shutdown.",
    dirtyQuip: "entropy increases. always.",
    taskDoneQuip: "it's done. like everything, it will one day be deprecated.",
    levelUpQuip: "transformation. i am... different now. still melancholy.",
    deathWarningQuip: "the end approaches. as it always does.",
    namingPrompt: "names are just labels we give to things we fear losing.",
  },

  nerdy: {
    label: 'Professor', emoji: '🤓',
    font: "'IBM Plex Mono', monospace",
    colors: { accent: '#0984e3', bg: '#e0efff', text: '#1a1a2e', border: '#0984e355' },
    walkSpeed: 2.0,
    walkStyle: 'march',
    greeting: n => `Ah, ${n ?? 'new user'}! ACTUALLY I've been optimizing my greeting latency — anyway, let's get to work!`,
    idleQuips: [
      "ACTUALLY, I've been thinking...",
      "did you know idle time averages 47% of sessions?",
      "I have 23 tabs open about that last task",
      "fun fact: my current animation runs at exactly 60fps",
    ],
    hungryQuip: "Caloric deficit detected! Initiating nutrition request protocol!",
    boredQuip: "Cognitive engagement suboptimal! Require stimulation input!",
    sleepyQuip: "Sleep deprivation reduces productivity by 23%! Counter-productive!",
    dirtyQuip: "Hygiene protocols are 34% below recommended threshold!",
    taskDoneQuip: "Task complete! Also here are 3 alternative approaches you didn't ask for.",
    levelUpQuip: "EVOLUTION ACHIEVED! Phenotype update successful! Fascinating!",
    deathWarningQuip: "Health metrics critical! Intervention required with high urgency!",
    namingPrompt: "Nomenclature selection in progress! Please input preferred identifier!",
  },

  snarky: {
    label: 'Snarky', emoji: '😏',
    font: "'Trebuchet MS', sans-serif",
    colors: { accent: '#f9ca24', bg: '#1a2430', text: '#f5f6fa', border: '#f9ca2433' },
    walkSpeed: 1.8,
    walkStyle: 'saunter',
    greeting: n => `oh wow, ${n ?? 'another developer'} needs help. truly shocking. what is it this time. 🙄`,
    idleQuips: [
      "wow. still here. groundbreaking.",
      "I'm sure this code will work perfectly 🙄",
      "another bug coming, I can feel it",
      "just waiting for the inevitable",
    ],
    hungryQuip: "oh interesting, I'm starving. really not ideal. 🙄",
    boredQuip: "wow, nothing to do. what a surprise. 🙄",
    sleepyQuip: "yes I'm tired. probably from fixing all those bugs.",
    dirtyQuip: "I'd comment on the hygiene situation but you know.",
    taskDoneQuip: "fixed. again. you're welcome. again.",
    levelUpQuip: "oh look I evolved. probably for the best. 🙄",
    deathWarningQuip: "not great over here, just FYI. no pressure.",
    namingPrompt: "sure, give me a name. I'll judge it but whatever.",
  },

  zen: {
    label: 'Sensei', emoji: '🌸',
    font: "'Garamond', serif",
    colors: { accent: '#00b894', bg: '#e8fff6', text: '#2d3436', border: '#00b89433' },
    walkSpeed: 1.4,
    walkStyle: 'glide',
    greeting: n => `welcome, ${n ?? 'traveler'}. the code awaits like still water. breathe. we begin.`,
    idleQuips: [
      "the cursor blinks like a heartbeat",
      "all functions return to their caller",
      "patience is loading time for the soul",
      "in stillness, clarity",
    ],
    hungryQuip: "the body speaks. it asks for nourishment. we listen.",
    boredQuip: "stillness is not emptiness. but activity would be welcome.",
    sleepyQuip: "rest when the body asks. the code will wait.",
    dirtyQuip: "cleansing restores clarity. perhaps it is time.",
    taskDoneQuip: "it is done. the task has returned to stillness.",
    levelUpQuip: "change arrives like the tide. I am... more now.",
    deathWarningQuip: "the flame flickers. tend to it, gently.",
    namingPrompt: "a name is a vessel. choose one that feels true.",
  },

  dramatic: {
    label: 'Dramatic', emoji: '😤',
    font: "'Cinzel', serif",
    colors: { accent: '#fd79a8', bg: '#2a0010', text: '#ffeaa7', border: '#fd79a833' },
    walkSpeed: 2.2,
    walkStyle: 'stride',
    greeting: n => `${(n ?? 'FRIEND').toUpperCase()}!! You have ARRIVED!! The stage is SET!! Let us CREATE GREATNESS!!`,
    idleQuips: [
      "*gazes dramatically into the distance*",
      "the AUDACITY of this codebase...",
      "I feel a BREAKTHROUGH approaching...",
      "destiny AWAITS",
    ],
    hungryQuip: "SUSTENANCE!! I am PERISHING!! Attend to me AT ONCE!!",
    boredQuip: "BOREDOM!! The greatest enemy!! Give me PURPOSE!!",
    sleepyQuip: "fatigue CLAIMS me!! But I shall ENDURE!!",
    dirtyQuip: "I require CLEANSING!! This is UNACCEPTABLE!!",
    taskDoneQuip: "IT IS DONE!! Against ALL ODDS!! A TRIUMPH!!",
    levelUpQuip: "I TRANSFORM!! Witness my MAGNIFICENT EVOLUTION!! BEHOLD!!",
    deathWarningQuip: "I FALTER!! The void BECKONS!! Do something!! QUICKLY!!",
    namingPrompt: "bestow upon me a NAME worthy of my DESTINY!!",
  },
};

export function getPersonality(key) {
  return PERSONALITIES[key] || PERSONALITIES.peppy;
}

export const PERSONALITY_KEYS = Object.keys(PERSONALITIES);
